#nullable enable

// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using DocumentFormat.OpenXml.Wordprocessing;
using Docxodus;
using Xunit;

namespace Docxodus.Tests;

/// <summary>
/// Regression tests for issue #302: a docxodus-saved .docx extracted with mode <c>000</c> (unreadable)
/// under a standard Unix <c>unzip</c>, because re-saving a package leaves zip central-directory
/// <c>ExternalAttributes</c> at 0 while stamping a Unix host byte on the archive. Word, LibreOffice,
/// and Python's <c>zipfile</c> don't consult these bits, so the bug is invisible except to tools that
/// do (e.g. <c>unzip</c>). Test IDs follow the <c>DS###</c> convention shared with
/// <see cref="DocxSessionTests"/>, continuing after DS345.
///
/// <para>The fixture matters: a document built by <see cref="DocxSession.CreateBlankDocxBytes"/> or
/// <see cref="DocumentBuilder"/> already gets non-zero <c>ExternalAttributes</c> baked in by the SDK
/// at creation time, so round-tripping it through an unrelated save path can pass even without the
/// fix — it never touches the actually-broken code path. A genuine Word-authored file has
/// <c>ExternalAttributes == 0</c> on every entry (Word doesn't set them), which is the baseline that
/// reproduces the bug; these tests load <c>TestFiles/Blank-wml.docx</c> for exactly that reason.</para>
/// </summary>
public class ZipUnixPermissionFixerTests
{
    private static byte[] LoadWordAuthoredFixture() =>
        File.ReadAllBytes(Path.Combine("../../../../TestFiles/", "Blank-wml.docx"));

    /// <summary>Every zip entry in <paramref name="docxBytes"/> must carry non-zero Unix permission bits.</summary>
    private static void AssertAllEntriesHaveUnixPermissions(byte[] docxBytes)
    {
        // The bug (and its fix) only concerns hosts where `unzip` interprets these bits at all.
        if (OperatingSystem.IsWindows())
            return;

        using var ms = new MemoryStream(docxBytes);
        using var zip = new ZipArchive(ms, ZipArchiveMode.Read);
        Assert.NotEmpty(zip.Entries);
        foreach (var entry in zip.Entries)
        {
            Assert.True(entry.ExternalAttributes != 0,
                $"entry '{entry.FullName}' has ExternalAttributes == 0 — would extract as mode 000 under unzip");
            var permissionBits = (entry.ExternalAttributes >> 16) & 0x1FF;
            Assert.True(permissionBits != 0,
                $"entry '{entry.FullName}' has zero Unix permission bits");
        }
    }

    [Fact]
    public void DS346_WordAuthoredFixture_HasTheZeroAttributeBaselineThisBugNeeds()
    {
        // Sanity check on the fixture itself: Word never sets these bits, so every entry starts at
        // exactly the value that the DocxSession.Save() bug fails to correct. If this ever stops
        // being true (e.g. the fixture is regenerated by a tool that does set them), DS347/DS348
        // would silently stop exercising the bug — this pins the precondition.
        using var ms = new MemoryStream(LoadWordAuthoredFixture());
        using var zip = new ZipArchive(ms, ZipArchiveMode.Read);
        Assert.All(zip.Entries, e => Assert.Equal(0, e.ExternalAttributes));
    }

    [Fact]
    public void DS347_SessionSavedFromExistingWordDocx_HasNonZeroUnixPermissions()
    {
        // The exact repro from issue #302: open a session from an EXISTING, real Word-authored
        // package, edit it, and save — the round trip that reproduced mode 000 under unzip.
        using var session = new DocxSession(LoadWordAuthoredFixture());

        var firstParagraph = session.Project().AnchorIndex.Keys.First();
        var edited = session.ReplaceText(firstParagraph, "Edited paragraph text.");
        Assert.True(edited.Success);

        var saved = session.Save();
        AssertAllEntriesHaveUnixPermissions(saved);
    }

    [Fact]
    public void DS348_SessionSavedTwice_BothSavesHaveNonZeroUnixPermissionsAndSessionStaysUsable()
    {
        // Guards against a fixer implementation that mutates the session's live backing stream:
        // a second edit + save on the SAME session must still work and still be fixed, proving the
        // first Save() call didn't corrupt state the open WordprocessingDocument depends on.
        using var session = new DocxSession(LoadWordAuthoredFixture());

        var anchor = session.Project().AnchorIndex.Keys.First();
        Assert.True(session.ReplaceText(anchor, "First edit.").Success);
        var saved1 = session.Save();
        AssertAllEntriesHaveUnixPermissions(saved1);

        Assert.True(session.ReplaceText(anchor, "Second edit.").Success);
        var saved2 = session.Save();
        AssertAllEntriesHaveUnixPermissions(saved2);

        using var reopened = new DocxSession(saved2);
        Assert.Contains("Second edit.", reopened.Project().Markdown);
    }

    [Fact]
    public void DS349_DocumentBuilderOutputFromExistingWordDocx_HasNonZeroUnixPermissions()
    {
        // Covers the OpenXmlMemoryStreamDocument.GetModified*Document() choke point shared by
        // DocumentBuilder/WmlComparer/HtmlToWmlConverter/etc. — the library-wide half of the fix,
        // independent of DocxSession, exercised against the same zero-attribute baseline.
        var wmlDoc = new WmlDocument("Blank-wml.docx", LoadWordAuthoredFixture());

        var sources = new List<Source> { new Source(wmlDoc, keepSections: true) };
        var built = DocumentBuilder.BuildDocument(sources);

        AssertAllEntriesHaveUnixPermissions(built.DocumentByteArray);
    }
}
